# Generated by Django 4.2.29 on 2026-03-25 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name / headline of this service.', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(help_text='URL-friendly identifier, auto-generated from the title.', max_length=255, unique=True, verbose_name='Slug')),
                ('intro', models.TextField(help_text='A short introductory paragraph shown in listings and teasers.', verbose_name='Intro text')),
                ('content', models.TextField(blank=True, help_text='Full HTML content for this service. Use the rich-text editor.', verbose_name='Content')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this service from the public site.', verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='Main visual for this service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title'],
            },
        ),
    ]
