# Generated by Django 4.2.30 on 2026-04-08 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('icon', models.CharField(blank=True, help_text="Optional icon identifier, e.g. 'fa-swimming-pool'.", max_length=100, verbose_name='icon CSS class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'amenity',
                'verbose_name_plural': 'amenities',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'amenity category',
                'verbose_name_plural': 'amenity categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('location_type', models.CharField(choices=[('country', 'Country'), ('state', 'State / Province'), ('city', 'City'), ('neighborhood', 'Neighborhood')], default='city', max_length=20, verbose_name='type')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('land', 'Land'), ('commercial', 'Commercial'), ('office', 'Office')], default='house', max_length=20, verbose_name='property type')),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('sale_and_rent', 'For Sale & Rent')], default='sale', max_length=20, verbose_name='listing type')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='bedrooms')),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='bathrooms')),
                ('parking_spaces', models.PositiveSmallIntegerField(default=0, verbose_name='parking spaces')),
                ('construction_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='construction area (m²)')),
                ('lot_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='lot area (m²)')),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year built')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='sale price')),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='rental price')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('MXN', 'MXN'), ('CAD', 'CAD'), ('COP', 'COP')], default='USD', max_length=3, verbose_name='currency')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity', verbose_name='amenities')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.location', verbose_name='location')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('is_cover', models.BooleanField(default=False, verbose_name='cover image')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='property')),
            ],
            options={
                'verbose_name': 'property image',
                'verbose_name_plural': 'property images',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.amenitycategory', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='PropertyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(help_text='URL-friendly identifier (per language).', max_length=255, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='properties.property')),
            ],
            options={
                'verbose_name': 'property Translation',
                'db_table': 'properties_property_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
