# Generated by Django 4.2.30 on 2026-04-08 02:24

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=properties.models.property_image_upload_to, verbose_name='image'),
        ),
    ]
