# Generated by Django 4.2.30 on 2026-04-08 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertyimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_published_status', models.BooleanField(default=False, help_text='If checked, properties with this status appear on the public site.', verbose_name='counts as published')),
            ],
            options={
                'verbose_name': 'property status',
                'verbose_name_plural': 'property statuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_published',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.propertystatus', verbose_name='status'),
        ),
    ]
